git clone git@bitbucket.org:pietto/bitbucket.git bitbucket-cloud
git clone git@bitbucket.org:pietto/jenkins.git jenkins-cloud
git clone git@bitbucket.org:pietto/jenkinsinter.git jenkinsinter-cloud
git clone git@bitbucket.org:pietto/test1.git test1-cloud
git clone git@bitbucket.org:pietto/test2.git test2-cloud
git clone git@bitbucket.org:pietto/test3.git test3-cloud
git clone git@bitbucket.org:pietto/test4.git test4-cloud
git clone git@bitbucket.org:pietto/test5.git test5-cloud
git clone git@bitbucket.org:pietto/test6.git test6-cloud
git clone git@bitbucket.org:pietto/test7.git test7-cloud
